### ISSUE TITLE
Synchronizing two sensors

### ISSUE THREAD

**Issue by kozuch** [sparkfun/Qwiic_IR_Array_MLX90640_55#1]
Is it possible to frame-synchronize two MLX90640 sensors so that they take a reading (image) exactly at the same time? Is it possible to have a synchronized "video stream" from two sensors where the individual frames are in sync?

**Comment by nseidle** [comment]
Duplicate, answered [here](https://github.com/sparkfun/SparkFun_MLX90640_Arduino_Example/issues/8).
